<?php
namespace App\Command;



use Doctrine\Common\Persistence\ManagerRegistry;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputArgument;

class AppCreateTournamentCommand extends Command
{
    private $doctrine;
    protected static $defaultName = 'app:create-tournament';

    public function __construct(ManagerRegistry $doctrine)
    {
        parent::__construct();
        $this->doctrine = $doctrine;
    }


    protected function configure()
    {
        $this->setDescription('Create a tournement')
            ->addArgument("name", InputArgument::REQUIRED, "The tournement\");
            ->addArgument('date', InputArgument::REQUIRED, "The tournement");

        parent::configure(); // TODO: Change the autogenerated stub
    }
    
    protected
    
}
        
        
        
        
